name: grumpy_io
description: Basic IO utilities for the grumpy architecture.
version: 1.0.0
repository: https://github.com/necodeIT/grumpy_io
publish_to: none

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  crypto: ^3.0.7
  dio: ^5.9.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  grumpy:
    git:
      url: https://github.com/necodeIT/grumpy.git
  grumpy_annotations:
    git:
      url: https://github.com/necodeIT/grumpy_annotations.git
  json_annotation: ^4.10.0
  logging: ^1.3.0
  meta: ^1.17.0
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  lints: ^6.0.0
  test: ^1.25.6

dependency_overrides:
  grumpy:
    path: ../grumpy
  grumpy_annotations:
    path: ../grumpy_annotations
